name: MMOCORETOP
version: '1.0-SNAPSHOT'
main: viezl.mmocoretop.MMOCORETOP
api-version: '1.19'
commands:
  topplayers:
    description: Hiển thị danh sách top 10 người chơi có cấp độ cao nhất.
    usage: /topplayers